# ML ZOOMCAMP 24: HOMEWORK 1

### GONÇALO BERNARDO

In [68]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

# QUESTION 1

In [69]:
print(f"Pandas' version is {pd.__version__}.")

Pandas' version is 2.1.0.


## Load data:

In [70]:
laptops = pd.read_csv("laptops.csv")

In [71]:
laptops.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

# QUESTION 2

In [72]:
print(f"Dataset has {laptops.shape[0]} records.")

Dataset has 2160 records.


# QUESTION 3

In [73]:
print(f"Our dataset has {laptops['Brand'].nunique()} different brands.")

Our dataset has 27 different brands.


# QUESTION 4

In [74]:
print(f"The number of columns with missing values is {laptops.isna().any().sum()}.")

The number of columns with missing values is 3.


# QUESTION 5

In [75]:
print(f"The maximum final price of Dell notebooks is {laptops[laptops['Brand']=='Dell']['Final Price'].max()} (dollars/euros).")

The maximum final price of Dell notebooks is 3936.0 (dollars/euros).


# QUESTION 6

In [76]:
#1. Find the median value of Screen column in the dataset
screen_median = laptops['Screen'].median()
screen_median

15.6

In [77]:
#2. Next, calculate the most frequent value of the same Screen column.
screen_mode = laptops["Screen"].mode().values[0]
screen_mode

15.6

In [78]:
#3. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
laptops["Screen"]=laptops["Screen"].fillna(screen_mode)
laptops[laptops["Screen"].isna()]["Screen"].count()

0

In [79]:
#4. Now, calculate the median value of Screen once again.
screen_median_2 = laptops['Screen'].median()
screen_median_2

15.6

### Has it changed?

In [80]:
assert screen_median == screen_median_2

# QUESTION 7

In [81]:
#1. Select all the "Innjoo" laptops from the dataset
#2. Select only columns RAM, Storage, Screen
#3. Get the underlying NumPy array. Let's call it X
X_ = laptops[laptops["Brand"]=="Innjoo"][["RAM","Storage","Screen"]]
X = X_.to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [82]:
#4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX
XTX = X.T @ X #np.linalg.linalg.matmul(X.T,X) would be an alternative
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [83]:
#5. Compute the inverse of XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [84]:
#6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [85]:
#7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w
aux_mult = XTX_inv @ X.T
u = aux_mult @ y
print(f"The sum of the array elements is {round(u.sum(),2)}.")

The sum of the array elements is 91.3.
